### ISSUE TITLE
Not work in GO version 1.5

### ISSUE THREAD

**Issue by nmfzone** [asib/spaceinvaders#4]
Is this just support for GO version 1.2?

Because when i try to "go build" in my terminal, i just got the following error : 

github.com/asib/spaceinvaders
./game.go:13: import /home/nmfcomp/Programming/GO/Work/pkg/linux_amd64/github.com/nsf/termbox-go.a: object is [linux amd64 go1.2.1 X:none] expected [linux amd64 go1.5 X:none]

Thanks in advance. Good working.

**Comment by asib** [comment]
Can you try what's suggested [here](https://groups.google.com/forum/#!topic/golang-nuts/s7zgGfmZ-aA) and let me know how it goes?

edit: I just built the whole thing from scratch on a fresh ubuntu box using go 1.5 so it should work fine
