### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by roopakv** [asib/spaceinvaders#5]
This game is installable via brew. in order to maintain go 1.17 support as well make maintenance easier could the maintainers please add go module support.

Homebrew/homebrew-core#47627

**Comment by asib** [comment]
@roopakv does latest commit fix the problem?

**Comment by chenrui333** [comment]
@asib thanks for the release, do you mind marking the latest release tag with "latest release" label? Thanks!

**Comment by asib** [comment]
@chenrui333 no problem, all done

**Comment by chenrui333** [comment]
Thank you!
